version: "3.7"
services:
  mongo:
    image: mongo:4.2.1-bionic
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - back-tier
  backend:
    build: .
    command: node /app/app.js
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - PORT=3000
    networks:
      - back-tier
      - front-tier
networks: 
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge