version: "3.7"
services:
  redis:
    image: redis:5.0.6-alpine
    networks:
      - back-tier
  backend:
    build: .
    command: node /app/app.js
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - PORT=3000
    networks:
      - back-tier
      - front-tier
networks: 
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge